### PR TITLE
`const None` can break methods due to `Never`

### PR DESCRIPTION
**Pull request by tim-smart**
Otherwise you get errors like:

```
type '() => Option<String>' is not a subtype of type '() => Option<Never>'
```

### CODE REVIEW

**Comment by SandroMaglione** [comment]
@tim-smart why do you think does this happen? On VSCode the result in inferred as `Option<String>` ([unnecessary_type_check](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unnecessary_type_check#unnecessary_type_check)), but when checking using `is` it returns the error. Could this be a bug in dart?

Screenshot 2023-02-26 at 12 03 00

**Comment by tim-smart** [comment]
Static analysis and the actual type at runtime can be different.

Generally all const instances have a generic type of `Never`, so I'm not exactly sure how const factories with generics actually work.

**Comment by SandroMaglione** [comment]
@tim-smart I opened [an issue on the dart language repository](https://github.com/dart-lang/language/issues/2869) to make sure this is something expected or not.

**Comment by tim-smart** [comment]
Yeah we will have to embrace `Never`, as I have just added a failing test that demonstrates how it could sneak into code.

**Comment by tim-smart** [comment]
The fix isn't ideal, as you have to drop some type classes for it to work.

To work around `Never` you have to use extension methods, which obviously can't implement overrides.
This means either:

1. Keeping the type classes but allowing `const None` to break code.
2. Dropping the type classes and embrace `const None`

I would lean towards option 2, as having reliable code without edge cases is generally more important than features that might not be used.

**Comment by SandroMaglione** [comment]
#### Review @tim-smart 

Methods removed from `Option`:
- `foldLeft`
- `foldRight`
- `foldMap`
- `foldRightWithIndex`
- `foldLeftWithIndex`
- `length`
- `any`
- `all`
- `concatenate`
- `plus`
- `prepend`
- `append`

These methods are now inside an extension:
- `alt`
- `getOrElse`
- `elem`

**Comment by SandroMaglione** [comment]
@tim-smart thanks for the great work 🙏🏼

**Comment by RandalSchwartz** [comment]
I guess this will get easier with patterns... but as long as ".map" works, I don't think this breaks any code I've written so far.  But that's a scary number of methods to go away.

**Comment by tim-smart** [comment]
> I guess this will get easier with patterns... but as long as ".map" works, I don't think this breaks any code I've written so far.  But that's a scary number of methods to go away.

While scary on paper, those methods are rarely used in practice.

`Alt` was the big one, which got moved to extension methods.

**Pull request merged**
