### PR TITLE
fix: fixed chainFirst returning Left result of chained method

### LINKED ISSUE #46: chainFirst only works for successful cases
When a chained `TaskEither` with `chainFirst` fails it propagates back which contradicts the documentation of `chainFirst` "ignore the result, and return the same value as the current [TaskEither]."

### PR DESCRIPTION
**Pull request by DevNico**
Closes #46

### CODE REVIEW

**Comment by DevNico** [comment]
You should probably add a `fail` call everywhere you do a `match` to expect something in either left or right cases since this way tests that should fail pass.

**Comment by SandroMaglione** [comment]
Hi @DevNico 

Good catch! You are right, `chainFirst` is incorrect when chaining fails.

Would you mind fixing `chainFirst` also in the other types? Namely:
- [x] `Either`
- [x] `TaskEither`
- [ ] `Monad`
- [ ] `State`
- [ ] `StateAsync`
- [ ] `Reader`
- [ ] `IOEither`

**Comment by DevNico** [comment]
I fixed the `IOEither` case. I have no experience using those other types and don't see them being broken just by looking at the code. If there is something wrong with the code there I suggest you fix it.

**Comment by SandroMaglione** [comment]
Great, thanks again for your contribution and suggestion 👍

**Comment by rd-martin-jaeger** [comment]
Hi @SandroMaglione @DevNico,

i have a general question about the function, regardless of how it is currently described in the documentation.
**Shouldn't `chainFirst()` actually be able to return any failures instead of ignoring them?**

Thats at least what i would expect when i start to chain eithers or did i miss the point, where it totally makes sense to ignore them within you chained functions?

Consequently, the previous solution would actually have been the right one for me.
```
flatMap((b) => chain(b).map((c) => b));
```


   ```
group('chainFirst', () {
       test('Right', () async {
        final task = TaskEither<String, int>.of(10);

        final chain = task.chainFirst((b) => TaskEither.right(100));

        final result = await chain.run();

        result.match(
          (l) => fail('should be right'),
          (r) => expect(r, 10),
        );
      });

      group('Left', () {
        test('from task', () async {
          final task = TaskEither<String, int>.of(10);

          final chain = task.chainFirst((b) => TaskEither.left('none'));

          final result = await chain.run();

          result.match(
            (l) => expect(l, 'none'),
            (r) => fail('should be left'),
          );
        });
      });
    });
```

**Comment by SandroMaglione** [comment]
Hi @rd-martin-jaeger 

If you need to return any failure you should use `flatMap`. `chainFirst` instead is used precisely for ignoring: you chain some computations without collecting its result.

**Pull request merged**
